spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
    username: postgres.hqejfkrouydmkhqzbnhp
    password: davijuvino123
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslmode: require
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
